image: node:18.16.0-bookworm

pipelines:
  branches:
    CFVM-153-icon-pipeline:
      - step:
          name: Check Icon Changes and Generate Icon Components
          condition:
            changesets:
              includePaths:
                - .icona/icons.json
          script:
            - npm install
            - npm run transform-icons
          artifacts:
            - icons/**
      - parallel:
        - step:
            name: Push to RN Design System
            condition:
              changesets:
                includePaths:
                  - .icona/icons.json
            script:
              - git clone https://x-token-auth:$RN_ACCESS_TOKEN@bitbucket.org/publyproduct/rn-design-system.git target
              - mkdir -p target/src/icons
              - rm -rf target/src/icons/*
              - cp -R icons/rn/* target/src/icons
              - cd target
              - git checkout -b CFVM-153-icon-pipeline
              - git config user.email $RN_BOT_EMAIL
              - git add .
              - git commit -a -m "[Updated Icons]"
              - git push --set-upstream https://x-token-auth:$RN_ACCESS_TOKEN@bitbucket.org/publyproduct/rn-design-system.git CFVM-153-icon-pipeline
              - cd .. 
        - step:
            name: Push to Web Design System
            condition:
              changesets:
                includePaths:
                  - .icona/icons.json
            script:
              - git clone https://x-token-auth:$WEB_ACCESS_TOKEN@bitbucket.org/publyproduct/web-design-system.git target
              - mkdir -p target/src/icons
              - rm -rf target/src/icons/*
              - cp -R icons/web/* target/src/icons
              - cd target
              - git checkout -b CFVM-153-icon-pipeline
              - git config user.email $WEB_BOT_EMAIL
              - git add .
              - git commit -a -m "[Updated Icons]"
              - git push --set-upstream https://x-token-auth:$WEB_ACCESS_TOKEN@bitbucket.org/publyproduct/web-design-system.git CFVM-153-icon-pipeline
              - cd .. 
        
              

